import Head from "next/head";
import React from "react";
import Cta from "../../../components/Cta";
import Div from "../../../components/Div";
import Layout from "../../../components/Layout";
import PageHeading from "../../../components/PageHeading";
import Pagination from "../../../components/Pagination";
/* import PostStyle2 from '../../../components/Post/PostStyle2'; */
/* import Sidebar from '../../../components/Sidebar'; */
import Spacing from "../../../components/Spacing";
import Link from "next/link";
import Image from "next/image";
import { Icon } from "@iconify/react";

/* import { GetStaticProps } from 'next' */
export async function getServerSideProps({ query }) {
  const page = query.page || 6
  const res = await fetch(`https://designgram.io/wp-json/wp/v2/posts?_embed&order=desc&per_page=${page}`);

  
  const data = await res.json();
  return {
    
    props: { data } 

};

  // code
}

export default function Blog({ data }) {
  console.log(data); 

  return (
    <>
      <Head>
        <title>Anagram - Blogs 📝 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Stay Ahead
        of The Curve"
          subtitle="We are an organic search engine optimization (SEO) agency that deploys proven SEO techniques and strategies that have helped many brands claim the top position on search engine results pages for competitive, high-volume industry keywords. Our SEO works — we know how to drive qualified traffic and keep your CAC low in the long term."
          pageLinkText="Blog"
        />

        <Div className="container">
          <Div className="row">
            {data.map((post, index) => (
              <Div className="col-lg-4" key={index}>
                <Div>
                  {post["_embedded"]["wp:featuredmedia"] &&
                    post["_embedded"]["wp:featuredmedia"][0] && (
                      <Image
                        src={
                          post["_embedded"]["wp:featuredmedia"][0]["source_url"]
                        }
                        width={500}
                        height={500}
                        alt="blog"
                      />
                    )}
                  <Spacing lg="10" md="10" />
                  <Link href={`/blog/${post["slug"]}`}>
                    <h4>{post["title"]["rendered"]}</h4>
                  </Link>
                  <div
                    dangerouslySetInnerHTML={{
                      __html: post["excerpt"]["rendered"],
                    }}
                  />
                  {/*  <p> dangerouslySetInnerHTML={{ __['excerpt']['rendered']html: post }}</p> */}
                </Div>

                <Spacing lg="40" md="40" />
              </Div>
            ))}

            <ul className="cs-pagination_box cs-center cs-white_color cs-mp0 cs-semi_bold">
              <li>
                <Link
                  className="cs-pagination_item cs-center active"
                  href="/blog"
                >
                  1
                </Link>
              </li>
              <li>
                <Link className="cs-pagination_item cs-center" href="/blog">
                  2
                </Link>
              </li>
              <li>
                <Link className="cs-pagination_item cs-center" href="/blog">
                  3
                </Link>
              </li>
              <li>
                <Link className="cs-pagination_item cs-center" href="/blog">
                  4
                </Link>
              </li>
              <li>
                <Link href="#" className="cs-pagination_item cs-center">
                  <Icon icon="akar-icons:chevron-right" />
                </Link>
              </li>
            </ul>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />something cool together 🚀"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
      </Layout>
    </>
  );
}
