import Head from "next/head";
import React from "react";
import Link from "next/link";

import Cta from "../../../components/Cta";
import Div from "../../../components/Div";
import Layout from "../../../components/Layout";
import PageHeading from "../../../components/PageHeading";

import TestimonialSlider from '../../../components/Slider/TestimonialSlider';
import Spacing from "../../../components/Spacing";
import { Icon } from "@iconify/react";


export default function Service() {
  return (
    <>
      <Head>
        <title>Anagram - Services 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="We have the services you need to get to your growth destination."
          subtitle="We build full-funnel solutions that power results-driven growth.

          Introducing the NoGood formula of strategy, experimentation and refinement. From hypotheses to insights, we are in constant scientific pursuit of the perfect balance between data and creativity that brands need to maximize their revenue potential."
          bgSrc="images/service_hero_bg.jpeg"
          pageLinkText="Services"
        />
        <Spacing lg="80" md="50" />
        <section className="container">
          <div className="row">
            <div className="col-md-6">
              <div className="cs-pricing_table cs-style1">
                <h2 className="cs-pricing_title">SEO</h2>
                <div className="cs-pricing_info">
                  <div className="cs-price">
                    <h4 className="cs-white_color">
                      We develop top-ranking content that targets specific
                      industry niches and captures high-intent traffic.
                    </h4>
                  </div>
                 
                </div>
              {/*   <ul className="cs-pricing_feature cs-mp0">
                  <li>
                    <span className="cs-feature_icon cs-accent_color">
                      <Icon icon="bi:arrow-right-circle" />
                    </span>
                    <span>Static responsive website</span>
                  </li>
                  <li>
                    <span className="cs-feature_icon cs-accent_color">
                      <Icon icon="bi:arrow-right-circle" />
                    </span>
                    <span>Video marketing</span>
                  </li>
                  <li>
                    <span className="cs-feature_icon cs-accent_color">
                      <Icon icon="bi:arrow-right-circle" />
                    </span>
                    <span>Keywords research</span>
                  </li>
                  <li>
                    <span className="cs-feature_icon cs-accent_color">
                      <Icon icon="bi:arrow-right-circle" />
                    </span>
                    <span>Facebook campaign</span>
                  </li>
                  <li>
                    <span className="cs-feature_icon cs-accent_color">
                      <Icon icon="bi:arrow-right-circle" />
                    </span>
                    <span>eCommerce solution</span>
                  </li>
                  <li>
                    <span className="cs-feature_icon cs-accent_color">
                      <Icon icon="bi:arrow-right-circle" />
                    </span>
                    <span>Google adword</span>
                  </li>
                </ul> */}
                <div className="cs-pricing_btn_wrap">
                  <Link href="/" className="cs-text_btn">
                    <span> View More</span>
                    <Icon icon="bi:arrow-right" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-md-6">
              <div className="cs-pricing_table cs-style1">
                <h2 className="cs-pricing_title">PUBLIC RELATIONS</h2>
                <div className="cs-pricing_info">
                  <div className="cs-price">
                    <h4 className="cs-white_color">
                      We develop top-ranking content that targets specific
                      industry niches and captures high-intent traffic.
                    </h4>
                  </div>
                 
                </div>
             
                <div className="cs-pricing_btn_wrap">
                  <Link href="/" className="cs-text_btn">
                    <span> View More</span>
                    <Icon icon="bi:arrow-right" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-md-6">
              <div className="cs-pricing_table cs-style1">
                <h2 className="cs-pricing_title">STRATEGIES & PRODUCTION</h2>
                <div className="cs-pricing_info">
                  <div className="cs-price">
                    <h4 className="cs-white_color">
                      We develop top-ranking content that targets specific
                      industry niches and captures high-intent traffic.
                    </h4>
                  </div>
                 
                </div>
              
                <div className="cs-pricing_btn_wrap">
                  <Link href="/" className="cs-text_btn">
                    <span> View More</span>
                    <Icon icon="bi:arrow-right" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-md-6">
              <div className="cs-pricing_table cs-style1">
                <h2 className="cs-pricing_title">PAY PER CLICK</h2>
                <div className="cs-pricing_info">
                  <div className="cs-price">
                    <h4 className="cs-white_color">
                      We develop top-ranking content that targets specific
                      industry niches and captures high-intent traffic.
                    </h4>
                  </div>
                
                </div>
            
                <div className="cs-pricing_btn_wrap">
                  <Link href="/" className="cs-text_btn">
                    <span> View More</span>
                    <Icon icon="bi:arrow-right" />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <Spacing lg="100" md="55" />
        <TestimonialSlider />
        <Spacing lg="30" md="30" />
        <Div className="container">
          <Cta
            title="Ready to kick off your
             <br />growth journey? 🚀"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
      </Layout>
    </>
  );
}
