import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Accordion from "../../../../components/Accordion";
import Button from "../../../../components/Button";
import Cta from "../../../../components/Cta";
import Div from "../../../../components/Div";
import IconBox from "../../../../components/IconBox";
import Layout from "../../../../components/Layout";
import PageHeading from "../../../../components/PageHeading";
import SectionHeading from "../../../../components/SectionHeading";
import TestimonialSlider from "../../../../components/Slider/TestimonialSlider";
import Spacing from "../../../../components/Spacing";
import Image from "next/image";
import Link from "next/link";

export default function ServiceDetails() {
  const router = useRouter();
  const serviceId = router.query.serviceId;
  return (
    <>
      <Head>
        <title>
          A Performance Marketing Agency That Innovates for Brands | Anagram
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Performance Marketing Agency With Data Driven Creative "
          subtitle="We combine purpose-driven storytelling and data-driven marketing strategies to enhance brand recall and maximize your MROI."
        />
        <Link href="#service" className="cs-down_btn cs_service_details_btn" scroll={false}>
          .
        </Link>

        <Spacing lg="120" md="50" />
        <Div className="container" id="service">
          <Div className="row align-items-center">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-radius_15 cs-shine_hover_1">
                <Image
                  src="/img/brand.svg"
                  alt="Service"
                  className="cs-radius_15 w-100"
                  width={445}
                  height={430}
                />
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            <Div className="col-lg-6 offset-xl-1">
              <h2 className="cs-font_50 cs-m0">
                Tell Your Brand Story, One Metric at a Time
              </h2>
              <h5>
                We debunk the common notion that creative and analytics don’t
                mix.
              </h5>
              <p>
                Our agile squad model operates at the intersection of creativity
                and performance, combining value-oriented brand strategy with
                data-focused performance across all channels and brand touch
                points. We are constantly testing creative brand fundamentals
                against audience metrics, and we use rapid experimentation at
                every stage of a measurable performance funnel to maximize ROI
                and increase brand LTV.
              </p>

              <Link className="cs-btn baner_btn_style" href="/contact">
                TALK TO US
              </Link>

              <Spacing lg="50" md="30" />
            </Div>
          </Div>
        </Div>
        <Spacing lg="120" md="50" />
        <Div className="container">
          <Div className="row align-items-center">
            <Div className="col-lg-6">
              <h2 className="cs-font_50 cs-m0">
                Marketing Strategies With Messaging Tailored to the Medium
              </h2>
              <h5>
                Tell the right story, at the right place, at the right time.
              </h5>
              <p>
                We refine your customer personas and segment your target
                audience to tailor your brand story to the channel it’s told
                through. With an intersectional strategy that considers both the
                brand, the audience and the channel, your customers will recieve
                a more unified and defined end-to-end experience, thus resulting
                in smarter learnings and more consistent impact.
              </p>

              <Link className="cs-btn baner_btn_style" href="/contact">
                START SCALING
              </Link>
            </Div>
            <Div className="col-xl-5 col-lg-5 offset-xl-1">
              <Div className="cs-radius_15 cs-shine_hover_1">
                <Image
                  src="/img/PerformanceBranding.png"
                  alt="Service"
                  className="cs-radius_15 w-100"
                  width={445}
                  height={430}
                />
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
          </Div>
        </Div>

        <Spacing lg="150" md="80" />

        <Div className="container">
          <h2 className="cs-font_50 cs-m0">Our Performance Marketing Tactics</h2>
          <Spacing lg="30" md="40" />
          <Div className="row align-items-center">
            <Div className="col-lg-4">
              <Button
                btnLink="#"
                btnText="UI/UX audit for SEO"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Site architecture"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Backlink analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Competitive analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Search Console setup"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Search Console setup"
                variant="cs-type2"
              />
              <Spacing lg="0" md="10" />
            </Div>
            <Div className="col-lg-4">
              <Button
                btnLink="#"
                btnText="Search Console setup"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Competitor analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Competitor analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Competitor analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Competitor analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Competitor analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
            </Div>
            <Div className="col-lg-4">
              <Button btnLink="#" btnText="Link building" variant="cs-type2" />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Site copy updates"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Image optimization"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Image optimization"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Competitor analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
              <Button
                btnLink="#"
                btnText="Competitor analysis"
                variant="cs-type2"
              />
              <Spacing lg="20" md="10" />
            </Div>
          </Div>
        </Div>
        <Spacing lg="80" md="80" />
        <TestimonialSlider />
        <Spacing lg="80" md="80" />
        <Div className="container cs-shape_wrap_4">
          <Div className="cs-shape_4"></Div>
          <Div className="cs-shape_4"></Div>
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-5 col-lg-6">
                <SectionHeading
                  title="Some pre questions and answers. 📖"
                  subtitle="FAQ’s"
                />
                <Spacing lg="90" md="45" />
              </Div>
              <Div className="col-lg-6 offset-xl-1">
                <Accordion />
              </Div>
            </Div>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Ready to kick off your <br/> growth journey? 🚀"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/img/cta_bg.jpeg"
          />
        </Div>
      </Layout>
    </>
  );
}
