import React from "react";
import Head from "next/head";
import Image from "next/image";
import Div from '../../components/Div'
import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";
import Spacing from "../../components/Spacing";
import SectionHeading from "../../components/SectionHeading";
import FunFact from '../../components/FunFact'
import Cta from '../../components/Cta';
import AboutImg from '../../public/img/about_img_4.jpeg';
/* import Calltoaction from '../../components/Call-to-action' */

export default function about() {
  const funfaceData = [
    {
      title: 'Global Happy Clients',
      factNumber: '20K',
    },
    {
      title: 'Project Completed',
      factNumber: '40K',
    },
    {
      title: 'Team Members',
      factNumber: '245',
    },
    {
      title: 'Digital products',
      factNumber: '550',
    },
  ];
  return (
    <>
      <Head>
        <title>Anagram - About 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Page Heading Section */}
        <PageHeading
          title="Your trusted partner for business"
          subtitle="We are here to work with you and provide you marcom solutions with
          marketing and digital transformations. Our efficient and doable
          communication strategies speak for themselves and let our publics
          experience the change. Experience the pleasure of a finest
          communication cycle, where we not only create strategies but bring
          ROI,"
          bgSrc="img/about_hero_bg.jpeg"
          pageLinkText="About Us"
        />
        {/* End Page Heading Section */}

         {/* Start Fun Fact Section */}
         <Div className="container">
          <FunFact
            title="Our fun fact"
            subtitle="Sed ut perspiciatis unde omnis iste natus error voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis."
            data={funfaceData}
          />
        </Div>
        {/* End Fun Fact Section */}
        
        {/* Start Why Choose Section */}
        <Spacing lg="100" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-image_layer cs-style1">
                <Div className="cs-image_layer_in">
                  <Image
                    src={AboutImg}
                    alt="About"
                    className="w-100 cs-radius_15" width={479} height={479}
                  />
                </Div>
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            <Div className="col-xl-5 offset-xl-1 col-lg-6">
              <SectionHeading
                title="Highly experienced pepole with us"
                subtitle="Why Choose Us"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                  This is the main factor that sets us apart from our
                  competition and allows us to deliver a specialist business
                  consultancy service. Our team applies its wide-ranging
                  experience to determining. Through our years of experience,
                  we’ve also learned that while each channel.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                  This is the main factor that sets us apart from our
                  competition and allows us to deliver a specialist business
                  consultancy service. Our team applies its wide-ranging
                  experience to determining.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="0" />
              </SectionHeading>
            </Div>
          </Div>
        </Div>
        {/* End Why Choose Section */}
        
     {/*    <Calltoaction/> */}
         {/* Start CTA Section */}
         <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Now that we are Anagram,<br/>
            we will do the same for you."
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
