import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Accordion from "../../components/CareerOpen";

import Div from "../../components/Div";

import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";

import Spacing from "../../components/Spacing";

import Link from "next/link";

function careers() {
  return (
    <>
      <Head>
        <title>Anagram | Career</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Created Creative things with us"
          subtitle="we're always eager to meet fresh talent, so check out our position"
        />
        <Link
          href="#scroll_down"
          className="cs-down_btn cs_service_details_btn"
          scroll={false}
        >
          .
        </Link>

        <Spacing lg="120" md="50" />
        <Div className="container cs-shape_wrap_4" id="scroll_down">
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-10 col-lg-10 offset-lg-1">
                <Accordion />
              </Div>
            </Div>
          </Div>
        </Div>
        <Spacing lg="120" md="50" />
      </Layout>
    </>
  );
}

export default careers;
