/* eslint-disable react-hooks/rules-of-hooks */
import { React, useState } from "react";
import Head from "next/head";
import { Icon } from "@iconify/react";
import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";
import Spacing from "../../components/Spacing";
import Div from "../../components/Div";
import SectionHeading from "../../components/SectionHeading";
import ContactInfoWidget from "../../components/Widget/ContactInfoWidget";



export default function contact() {

 
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [name, setName] = useState("");
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [email, setEmail] = useState("");
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [number, setNumber] = useState("");
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [company, setCompany] = useState("");
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [message, setMessage] = useState("");
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [checked, setChecked] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await fetch("/api/sendEmail", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name,
          email,
          number,
          company,
          message,
          checked,
        }),
      });

      if (response.ok) {
        // Email sent successfully
        console.log("Email sent");
        // Reset form fields
        setName("");
        setEmail("");
        setNumber("");
        setCompany("");
        setMessage("");
        setChecked("");
      } else {
        // Error sending email
        console.error("Error sending email");
      }
    } catch (error) {
      console.error("Error sending email", error);
    }
  };


 
  return (
    <>
      <Head>
        <title>Anagram - Contact Us ☎️</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Page Heading Section */}
        <PageHeading
          title="Get in Touch"
          subtitle="Thank you for visiting our website, if you have any questions or comments, we would like to hear from you. Please contact us by filling out the form below or give us a call. For Enquiries email info@anagrammedia.tech"
          bgSrc="img/about_hero_bg.jpeg"
          pageLinkText="Contact"
        />
        {/* End Page Heading Section */}
        <Spacing lg="10" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-lg-6">
              <SectionHeading
                title="Ready to meet your Aanagram partner?"
                subtitle="We seek lasting relationships to help our clients unlock rapid growth at efficient economics. Tell us where you are and where you want to be."
              />
              <Spacing lg="55" md="30" />
              <ContactInfoWidget withIcon />
              <Spacing lg="0" md="50" />
            </Div>
            <Div className="col-lg-6">
              <form className="row" onSubmit={handleSubmit}>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">
                    Full Name<span className="color_red">*</span>
                  </label>
                  <input
                    type="text"
                    className="cs-form_field"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="Full Name"
                    required
                  />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">
                    Email<span className="color_red">*</span>
                  </label>
                  <input
                    type="email"
                    className="cs-form_field"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="Email"
                    required
                  />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">
                    Company<span className="color_red">*</span>
                  </label>
                  <input
                    type="text"
                    className="cs-form_field"
                    value={company}
                    onChange={(e) => setCompany(e.target.value)}
                    placeholder="Company"
                    required
                  />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">
                    Mobile<span className="color_red">*</span>
                  </label>
                  <input
                    type="text"
                    className="cs-form_field"
                    value={number}
                    onChange={(e) => setNumber(e.target.value)}
                    placeholder="Mobile Number"
                    required
                  />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-12">
                  <label className="cs-primary_color">
                    Message<span className="color_red">*</span>
                  </label>
                  <textarea
                    cols="30"
                    rows="3"
                    className="cs-form_field"
                    value={message}
                    onChange={(e) => setMessage(e.target.value)}
                    placeholder="Message"
                    required
                  ></textarea>
                  <Spacing lg="25" md="25" />
                </Div>
                <Div className="col-sm-12">
                  <div className="form-check">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      value={checked}
                      checked={checked}
                      onChange={(e) => setChecked(e.target.checked)}
                      id="flexCheckChecked"
                    />
                    <label
                      className="form-check-label"
                      htmlFor="flexCheckChecked"
                    >
                      Yes, I want to experience the greatest growth newsletter
                      on the internet.
                    </label>
                  </div>
                  <button className="cs-btn cs-style1">
                    <span>Send Message</span>
                    <Icon icon="bi:arrow-right" />
                  </button>
                </Div>
              </form>
            </Div>
          </Div>
        </Div>
        {/*  Google map */}
        <Spacing lg="150" md="80" />
        <Div className="cs-google_map">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d464.21433582473094!2d77.27197639441574!3d28.531312830070707!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce1dc90c67a1f%3A0xa2e2fbc1dd9fde37!2sAnagram%20Media%20Labs%20Pvt%20Ltd!5e0!3m2!1sen!2sin!4v1686215892134!5m2!1sen!2sin"
            allowFullScreen
            title="Google Map"
            loading="lazy"
          />
        </Div>
        <Spacing lg="50" md="40" />
       
      </Layout>
    </>
  );
}
