/* eslint-disable react/jsx-no-undef */
import Head from "next/head";
import Layout from "../../components/Layout";
import Spacing from "../../components/Spacing";
import Div from "../../components/Div";
import Link from "next/link";
import VerticalLinks from '../../components/VerticalLinks'

/* import Layout from '../../components/Layout'; */

export default function Home() {
   // Hero Social Links
   const heroSocialLinks = [
    {
      name: 'Facebook',
      links: 'https://www.facebook.com/anagrammedialabs',
    },
    {
      name: 'Twitter',
      links: 'https://twitter.com/anagram_media',
    },
    {
      name: 'Linkdin',
      links: 'https://www.linkedin.com/company/anagram-media-labs-pvt-ltd',
    },
    {
      name: 'Instagram',
      links: 'https://www.instagram.com/anagrammedia/',
    },
  ];

  return (
    <>
      <Head>
        <title>Anagram Media Labs 🏠 </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Spacing lg="180" md="50" />
        <Div className="cs-style1 cs-center text-center cs-bg">
          
          <Div className="container">
            <Div className="cs-page_heading_in">
              <h1 className="cs-page_title cs-font_90 cs-white_color">
                We Help Brands Establish 
              </h1>
              <div className="ms-slider">
                <ul className="ms-slider__words">
                  <li className="ms-slider__word">Sustainable.</li>
                  <li className="ms-slider__word">Predictable.</li>
                  <li className="ms-slider__word">Scalable.</li>
                {/*   <li class="ms-slider__word">Measurable</li> */}
                  {/*  <!-- This last word needs to duplicate the first one to ensure a smooth infinite animation --> */}
                  <li className="ms-slider__word">Sustainable.</li>
                </ul>
              </div>
              <p className="cs-white_color cs-margin_right_140 cs-margin_left_140">
                Increase your sales & ROI without agency fluff. we’ll safeguard
                your intersest by not spending uselessly. we make a firm
                foundation of long term strategies that you can reap reward of
                even without us. 
              </p>
              <VerticalLinks data={heroSocialLinks} title="Follow Us" />
              <Link href="#service" className="cs-down_btn">.</Link>
            </Div>
          </Div>
        </Div>
      </Layout>
    </>
  );
}
