import Head from "next/head";
import React from "react";
import Cta from "../../../components/Cta";
import Div from "../../../components/Div";
import Layout from "../../../components/Layout";
import BlogPageHeading from "../../../components/PageHeading";

/* import PostStyle2 from '../../../components/Post/PostStyle2'; */
import Sidebar from "../../../components/Sidebar";
import Spacing from "../../../components/Spacing";
import Link from "next/link";
import Image from "next/image";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Anagram - Privancy Policy 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <BlogPageHeading title="Privancy Policy" />
        <Spacing lg="10" md="30" />

        <Div className="container">
          <h3>Privacy policy </h3>
          <p>
            This privacy notice for Anagram Media Labs Pvt. Ltd. (doing business
            as AML) (`AML`, `we` , `us` or `our`), describes how and why we
            might collect, store, use, and/or share (`process`) your information
            when you use our services (`Services`), such as when you:Visit our
            website at{" "}
            <Link href="/" className="cs-white_color"> 
              www.anagrammedia.tech
            </Link>
            , or any website of ours that links to this privacy notice Engage
            with us in other related ways, including any sales, marketing, or
            events
          </p>
          <p>
            Questions or concerns? Reading this privacy notice will help you
            understand your privacy rights and choices. If you do not agree with
            our policies and practices, please do not use our Services. If you
            still have any questions or concerns, please contact us at
            <Link href="mailto:info@anagrammedia.tech" className="cs-white_color">
              
              info@anagrammedia.tech
            </Link>
          </p>
          <h3>Summary of key points</h3>
          <p>
            This summary provides key points from our privacy notice, but you
            can find out more details about any of these topics by clicking the
            link following each key point or by using our table of contents
            below to find the section you are looking for. You can also click
            here to go directly to our table of contents.
          </p>
          <p>
            What personal information do we process? When you visit, use, or
            navigate our Services, we may process personal information depending
            on how you interact with AML and the Services, the choices you make,
            and the products and features you use. Click here to learn more.
          </p>
          <p>
            Do we process any sensitive personal information? We do not process
            sensitive personal information.
          </p>
          <p>
            Do we receive any information from third parties? We may receive
            information from public databases, marketing partners, social media
            platforms, and other outside sources. Click here to learn more.
          </p>
          <p>
            Do we receive any information from third parties? We may receive
            information from public databases, marketing partners, social media
            platforms, and other outside sources. Click here to learn more.
          </p>
          <p>
            How do we process your information? We process your information to
            provide, improve, and administer our Services, communicate with you,
            for security and fraud prevention, and to comply with law. We may
            also process your information for other purposes with your consent.
            We process your information only when we have a valid legal reason
            to do so. Click here to learn more.
          </p>
          <p>
            In what situations and with which types of parties do we share
            personal information? We may share information in specific
            situations and with specific categories of third parties. Click here
            to learn more
          </p>
          <p>
            How do we keep your information safe? We have organizational and
            technical processes and procedures in place to protect your personal
            information. However, no electronic transmission over the internet
            or information storage technology can be guaranteed to be 100%
            secure, so we cannot promise or guarantee that hackers,
            cybercriminals, or other unauthorized third parties will not be able
            to defeat our security and improperly collect, access, steal, or
            modify your information. Click here to learn more.
          </p>
          <p>
            What are your rights? Depending on where you are located
            geographically, the applicable privacy law may mean you have certain
            rights regarding your personal information. Click here to learn
            more.
          </p>
          <p>
            How do you exercise your rights? The easiest way to exercise your
            rights is by filling out our data subject request form available
            here, or by contacting us. We will consider and act upon any request
            in accordance with applicable data protection laws.
          </p>
          <p>
            Want to learn more about what AML does with any information we
            collect? Click here to review the notice in full.
          </p>
          <h3>Table of contents :</h3>
          <ul>
            <li>WHAT INFORMATION DO WE COLLECT?</li>
            <li>HOW DO WE PROCESS YOUR INFORMATION?</li>
            <li> WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</li>
            <li>DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</li>
            <li>HOW LONG DO WE KEEP YOUR INFORMATION?</li>
            <li>HOW DO WE KEEP YOUR INFORMATION SAFE?</li>
            <li>DO WE COLLECT INFORMATION FROM MINORS?</li>
            <li>WHAT ARE YOUR PRIVACY RIGHTS?</li>
            <li>CONTROLS FOR DO-NOT-TRACK FEATURES</li>
            <li>DO WE MAKE UPDATES TO THIS NOTICE?</li>
            <li>HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</li>
          </ul>
          <h3>1. What information do we collect?</h3>
          <p>
            Personal information you disclose to us In Short: We collect
            personal information that you provide to us.
          </p>
          <p>
            We collect personal information that you voluntarily provide to us
            when you express an interest in obtaining information about us or
            our products and Services, when you participate in activities on the
            Services, or otherwise when you contact us. Personal Information
            Provided by You.
          </p>
          <p>
            The personal information that we collect depends on the context of
            your interactions with us and the Services, the choices you make,
            and the products and features you use. The personal information we
            collect may include the following:
          </p>
          <ul>
            <li>Names</li>
            <li>Phone numbers</li>
            <li>Email addresses</li>
            <li>Job titles</li>
            <li>Contact or authentication data</li>
          </ul>
          <p>
            Sensitive Information. We do not process sensitive information. All
            personal information that you provide to us must be true, complete,
            and accurate, and you must notify us of any changes to such personal
            information.
          </p>
          <p>
            Information automatically collected : In Short: Some information —
            such as your Internet Protocol (IP) address and/or browser and
            device characteristics — is collected automatically when you visit
            our Services.
          </p>
          <p>
            We automatically collect certain information when you visit, use, or
            navigate the Services. This information does not reveal your
            specific identity (like your name or contact information) but may
            include device and usage information, such as your IP address,
            browser and device characteristics, operating system, language
            preferences, referring URLs, device name, country, location,
            information about how and when you use our Services, and other
            technical information. This information is primarily needed to
            maintain the security and operation of our Services, and for our
            internal analytics and reporting purposes.
          </p>
          <p>
            Like many businesses, we also collect information through cookies
            and similar technologies.
          </p>
          <p>The information we collect includes:</p>
          <p>Log and Usage Data :</p>
          <p>
            Log and usage data is service-related, diagnostic, usage, and
            performance information our servers automatically collect when you
            access or use our Services and which we record in log files.
            Depending on how you interact with us, this log data may include
            your IP address, device information, browser type, and settings and
            information about your activity in the Services (such as the
            date/time stamps associated with your usage, pages and files viewed,
            searches, and other actions you take such as which features you
            use), device event information (such as system activity, error
            reports (sometimes called `crash dumps`), and hardware settings).
          </p>
          <p>
            Device Data : We collect device data such as information about your
            computer, phone, tablet, or other device you use to access the
            Services. Depending on the device used, this device data may include
            information such as your IP address (or proxy server), device and
            application identification numbers, location, browser type, hardware
            model, Internet service provider and/or mobile carrier, operating
            system, and system configuration information.
          </p>
          <p>
            Location Data. We collect location data such as information about
            your devices location, which can be either precise or imprecise. How
            much information we collect depends on the type and settings of the
            device you use to access the Services. For example, we may use GPS
            and other technologies to collect geolocation data that tells us
            your current location (based on your IP address). You can opt out of
            allowing us to collect this information either by refusing access to
            the information or by disabling your Location setting on your
            device. However, if you choose to opt out, you may not be able to
            use certain aspects of the Services.
          </p>
          <p>
            Information collected from other sources In Short: We may collect
            limited data from public databases, marketing partners, and other
            outside sources. In order to enhance our ability to provide relevant
            marketing, offers, and services to you and update our records, we
            may obtain information about you from other sources, such as public
            databases, joint marketing partners, affiliate programs, data
            providers, and from other third parties. This information includes
            mailing addresses, job titles, email addresses, phone numbers,
            intent data (or user behavior data), Internet Protocol (IP)
            addresses, social media profiles, social media URLs, and custom
            profiles, for purposes of targeted advertising and event promotion.
          </p>
          <h3>2. How do we process your information?</h3>
          <p>
            In Short: We process your information to provide, improve, and
            administer our Services, communicate with you, for security and
            fraud prevention, and to comply with law. We may also process your
            information for other purposes with your consent. We process your
            personal information for a variety of reasons, depending on how you
            interact with our Services, including:
          </p>
          <p>
            To deliver and facilitate delivery of services to the user. We may
            process your information to provide you with the requested service.
          </p>
          <p>
            To respond to user inquiries/offer support to users. We may process
            your information to respond to your inquiries and solve any
            potential issues you might have with the requested service.
          </p>

          <p>
            To send administrative information to you. We may process your
            information to send you details about our products and services,
            changes to our terms and policies, and other similar information.
          </p>
          <p>
            To fulfill and manage your orders. We may process your information
            to fulfill and manage your orders, payments, returns, and exchanges
            made through the Services.
          </p>
          <p>
            To enable user-to-user communications. We may process your
            information if you choose to use any of our offerings that allow for
            communication with another user.
          </p>
          <p>
            To request feedback. We may process your information when necessary
            to request feedback and to contact you about your use of our
            Services.
          </p>
          <p>
            To send administrative information to you. We may process your
            information to send you details about our products and services,
            changes to our terms and policies, and other similar information.
          </p>
          <p>
            To fulfill and manage your orders. We may process your information
            to fulfill and manage your orders, payments, returns, and exchanges
            made through the Services.
          </p>
          <p>
            To enable user-to-user communications. We may process your
            information if you choose to use any of our offerings that allow for
            communication with another user.
          </p>
          <p>
            To request feedback. We may process your information when necessary
            to request feedback and to contact you about your use of our
            Services.
          </p>
          <p>
            To send you marketing and promotional communications. We may process
            the personal information you send to us for our marketing purposes,
            if this is in accordance with your marketing preferences. You can
            opt out of our marketing emails at any time. For more information,
            see `WHAT ARE YOUR PRIVACY RIGHTS?` below.
          </p>
          <p>
            To deliver targeted advertising to you. We may process your
            information to develop and display personalized content and
            advertising tailored to your interests, location, and more.
          </p>
          <p>
            To post testimonials. We post testimonials on our Services that may
            contain personal information.
          </p>
          <p>
            To protect our Services. We may process your information as part of
            our efforts to keep our Services safe and secure, including fraud
            monitoring and prevention.
          </p>
          <p>
            To evaluate and improve our Services, products, marketing, and your
            experience. We may process your information when we believe it is
            necessary to identify usage trends, determine the effectiveness of
            our promotional campaigns, and to evaluate and improve our Services,
            products, marketing, and your experience.
          </p>
          <p>
            To identify usage trends. We may process information about how you
            use our Services to better understand how they are being used so we
            can improve them
          </p>
          <p>
            To determine the effectiveness of our marketing and promotional
            campaigns. We may process your information to better understand how
            to provide marketing and promotional campaigns that are most
            relevant to you.
          </p>
          <p>
            To comply with our legal obligations. We may process your
            information to comply with our legal obligations, respond to legal
            requests, and exercise, establish, or defend our legal rights.
          </p>
          <h3>3. When and with whom do we share your personal information?</h3>
          <p>
            <b>In Short : </b> We may share information in specific situations
            described in this section and/or with the following categories of
            third parties.
          </p>
          <p>
            Vendors, Consultants, and Other Third-Party Service Providers. We
            may share your data with third-party vendors, service providers,
            contractors, or agents &quot; third parties &quot; who perform
            services for us or on our behalf and require access to such
            information to do that work. We have contracts in place with our
            third parties, which are designed to help safeguard your personal
            information. This means that they cannot do anything with your
            personal information unless we have instructed them to do it. They
            will also not share your personal information with any organization
            apart from us. They also commit to protect the data they hold on our
            behalf and to retain it for the period we instruct. The categories
            of third parties we may share personal information with are as
            follows:
          </p>
          <ul>
            <li>Website Hosting Service Providers</li>
            <li>User Account Registration &amp; Authentication Services</li>
            <li>Testing Tools</li>
            <li>Social Networks</li>
            <li>Sales &amp; Marketing Tools</li>
            <li>Retargeting Platforms</li>
            <li>Product Engineering &amp; Design Tools</li>
            <li>Performance Monitoring Tools</li>
            <li>Payment Processors</li>
            <li>Order Fulfillment Service Providers</li>
            <li>Ad Networks</li>
            <li>Affiliate Marketing Programs</li>
            <li>Communication &amp; Collaboration Tools</li>
            <li>Cloud Computing Services</li>
            <li>Data Analytics Services</li>
            <li>Data Storage Service Providers</li>
          </ul>
          <p>
            We also may need to share your personal information in the following
            situations:
          </p>
          <p>
            <b>Business Transfer:</b>
            <br />
            We may share or transfer your information in connection with, or
            during negotiations of, any merger, sale of company assets,
            financing, or acquisition of all or a portion of our business to
            another company.
          </p>
          <p>
            <b>Affiliates :</b>
            <br /> We may share your information with our affiliates, in which
            case we will require those affiliates to honor this privacy notice.
            Affiliates include our parent company and any subsidiaries, joint
            venture partners, or other companies that we control or that are
            under common control with us.
          </p>
          <p>
            <b>Business Partners :</b>
            <br />
            We may share your information with our business partners to offer
            you certain products, services, or promotions.
          </p>
          <h3>4. Do we use cookies and other tracking technologies?</h3>
          <p>
            <b>In Short:</b> We may use cookies and other tracking technologies
            to collect and store your information.
          </p>
          <p>
            We may use cookies and similar tracking technologies (like web
            beacons and pixels) to access or store information. Specific
            information about how we use such technologies and how you can
            refuse certain cookies is set out in our Cookie Notice.
          </p>
          <h3>5. How long do we keep your information?</h3>
          <p>
            In Short: We keep your information for as long as necessary to
            fulfill the purposes outlined in this privacy notice unless
            otherwise required by law.
          </p>
          <p>
            We will only keep your personal information for as long as it is
            necessary for the purposes set out in this privacy notice, unless a
            longer retention period is required or permitted by law (such as
            tax, accounting, or other legal requirements).
          </p>
          <p>
            When we have no ongoing legitimate business need to process your
            personal information, we will either delete or anonymize such
            information, or, if this is not possible (for example, because your
            personal information has been stored in backup archives), then we
            will securely store your personal information and isolate it from
            any further processing until deletion is possible.
          </p>
          <h3>6. How do we keep your information safe?</h3>
          <p>
            <b>In Short:</b> We aim to protect your personal information through
            a system of organizational and technical security measures.
          </p>
          <p>
            We have implemented appropriate and reasonable technical and
            organizational security measures designed to protect the security of
            any personal information we process. However, despite our safeguards
            and efforts to secure your information, no electronic transmission
            over the Internet or information storage technology can be
            guaranteed to be 100% secure, so we cannot promise or guarantee that
            hackers, cybercriminals, or other unauthorized third parties will
            not be able to defeat our security and improperly collect, access,
            steal, or modify your information. Although we will do our best to
            protect your personal information, transmission of personal
            information to and from our Services is at your own risk. You should
            only access the Services within a secure environment
          </p>
          <h3>7. Do we collect information from minors?</h3>
          <p>
            <b>In Short:</b> We do not knowingly collect data from or market to
            children under 18 yearsof age.
          </p>
          <p>
            We do not knowingly solicit data from or market to children under 18
            years of age. By using the Services, you represent that you are at
            least 18 or that you are the parent or guardian of such a minor and
            consent to such minor dependent’s use of the Services. If we learn
            that personal information from users less than 18 years of age has
            been collected, we will deactivate the account and take reasonable
            measures to promptly delete such data from our records. If you
            become aware of any data we may have collected from children under
            age 18, please contact us at{" "}
            <Link href="mailto:info@anagrammedia.tech" className="cs-white_color">
              info@anagrammedia.tech
            </Link>
          </p>
          <h3>8. What are your privacy rights?</h3>
          <p>
            <b>In Short: </b>You may review, change, or terminate your account
            at any time.
          </p>
          <p>
            <b>Withdrawing your consent:</b>
            <br /> If we are relying on your consent to process your personal
            information, which may be express and/or implied consent depending
            on the applicable law, you have the right to withdraw your consent
            at any time. You can withdraw your consent at any time by contacting
            us by using the contact details provided in the section &duot;HOW
            CAN YOU CONTACT US ABOUT THIS NOTICE? &duot; below. However, please
            note that this will not affect the lawfulness of the processing
            before its withdrawal nor, when applicable law allows, will it
            affect the processing of your personal information conducted in
            reliance on lawful processing grounds other than consent.
          </p>
          <p>
            <b>Opting out of marketing and promotional communications:</b>
            <br />
            You can unsubscribe from our marketing and promotional
            communications at any time by clicking on the unsubscribe link in
            the emails that we send, or by contacting us using the details
            provided in the section &duot;HOW CAN YOU CONTACT US ABOUT THIS
            NOTICE? &duot; below. You will then be removed from the marketing
            lists. However, we may still communicate with you — for example, to
            send you service-related messages that are necessary for the
            administration and use of your account, to respond to service
            requests, or for other non-marketing purposes.
          </p>
          <p>
            Cookies and similar technologies: Most Web browsers are set to
            accept cookies by default. If you prefer, you can usually choose to
            set your browser to remove cookies and to reject cookies. If you
            choose to remove cookies or reject cookies, this could affect
            certain features or services of our Services. To opt out of
            interest-based advertising by advertisers on our Services visit
            http://www.aboutads.info/choices/. If you have questions or comments
            about your privacy rights, you may email us at
            <Link href="mailto: info@anagrammedia.tech" className="cs-white_color">
              {" "}
              info@anagrammedia.tech
            </Link>
          </p>
          <h3>9. Controls for do-not-track features</h3>
          <p>
            Most web browsers and some mobile operating systems and mobile
            applications include a Do-Not-Track &dout;DNT&duot; feature or
            setting you can activate to signal your privacy preference not to
            have data about your online browsing activities monitored and
            collected. At this stage no uniform technology standard for
            recognizing and implementing DNT signals has been finalized. As
            such, we do not currently respond to DNT browser signals or any
            other mechanism that automatically communicates your choice not to
            be tracked online. If a standard for online tracking is adopted that
            we must follow in the future, we will inform you about that practice
            in a revised version of this privacy notice.
          </p>
          <h3>10. Do we make updates to this notice?</h3>
          <p>
            <b>In Short:</b> Yes, we will update this notice as necessary to
            stay compliant with relevan Laws.
            <br /> We may update this privacy notice from time to time. The
            updated version will be indicated by an updated &dout;Revised&duot;
            date and the updated version will be effective as soon as it is
            accessible. If we make material changes to this privacy notice, we
            may notify you either by prominently posting a notice of such
            changes or by directly sending you a notification. We encourage you
            to review this privacy notice frequently to be informed of how we
            are protecting your information.
          </p>
          <h3>11. How can you contact us about this notice?</h3>
          <p>
            If you have questions or comments about this notice, you may email
            us at <Link href="mailto:info@anagrammedia.tech" className="cs-white_color">info@anagrammedia.tech</Link> or by post to: <Link href="/" className="cs-white_color">Anagram Media Labs Pvt. Ltd </Link>
             A-89, Second Floor, Okhla Phase II, Okhla Industrial Area.
            Delhi, Delhi 110020 India
          </p>
        </Div>

        <Spacing lg="20" md="80" />
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />something cool together 🚀"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
      </Layout>
    </>
  );
}
